add_newline = false

# A minimal left prompt
format = """$os$directory$character"""
palette = "kitty_theme"

# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[directory.substitutions]
'~/work' = 'Projects'

[directory]
truncation_length = 3
truncate_to_repo = true
style = "blue"
read_only = " 󰌾"

[cmd_duration]
min_time = 100
format ='[󱎫 $duration ]($style)'
style = "surface2"

[git_branch]
symbol = "[ ](sapphire)"
format =  '[$symbol$branch(:$remote_branch) ](sapphire)'

[username]
disabled = false

[git_status]
conflicted = "[ $count](maroon) "
untracked = "[ $count](peach) "
modified = "[ $count](yellow) "
deleted = "[ $count](red) "
staged = "[ $count](green) "
renamed = "[ $count](surface2) "
style = 'bold subtext1'
ahead = '[⇡${count} ](green)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](yellow)'
behind = '[⇣${count} ](red)'
format = '([$all_status$ahead_behind]($style))'
stashed = "[ $count](mauve) "

[hostname]
ssh_symbol = " "

[os]
disabled = false

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[battery]
full_symbol = '󱈏 '
charging_symbol = ' '
discharging_symbol = '󰁾 '

[[battery.display]]
threshold = 50
style = 'bold teal'

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
format = '[$symbol]($style)'
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "


[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "


[shell]
bash_indicator = '󰈺 '
zsh_indicator = ''
style = 'cyan bold'
disabled = false

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "


[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
format ='[$symbol($version )]($style)'
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = " "
style = "dimmed white"

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]

format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.kitty_theme]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

