[pyprland]
plugins = [
  "scratchpads",
  "layout_center",
  "magnify",
  "expose",
  "workspaces_follow_focus",
  "shortcuts_menu",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.topTerm]
animation = "fromTop"
command = "kitty --class kitty-topTerm"
class = "kitty-topTerm"
size = "75% 40%"
lazy =true

[scratchpads.bottomTerm]
animation = "fromBottom"
command = "kitty --class kitty-bottomTerm"
class = "kitty-bottomTerm"
size = "75% 50%"
lazy =true

[scratchpads.mainterm]
animation = "fromBottom"
command = "kitty --class kitty-mainTerm"
class = "kitty-mainTerm"
size = "96% 93%"
pinned = false
lazy = false

[shortcuts_menu.entries]
"LocalHost" = 'zen-browser --new-tab "http://localhost:3000" &'
"Email" = "wl-copy abhidahal7@gmail.com"

# [shortcuts_menu.entries.Configs]
"Kitty" = "kitty  nvim ~/.config/kitty/kitty.conf"
"Hypr" = "kitty  nvim ~/.config/hypr/keybindings.conf"
"Scripts" = "kitty  nvim ~/.config/hyprdots/scripts"
"Nvim" = "kitty  nvim ~/.config/nvim"
"Aliases" = "kitty  nvim ~/.config/aliases/.bash_aliases"

[shortcuts_menu.entries."VPN"]
"Username" = "wl-copy HlCG6h1hfD8XAzPO"
"Password" = "wl-copy AU0JlbRmgLjQA0BrEoPK2ofvobyZp8f1"


[shortcuts_menu.entries.Hydra]
"code" = 'kitty  nvim ~/work/hydra-den-web/'
"Web Repo" = 'zen-browser --new-tab "https://github.com/h3cksamrat/hydra-den-web/" &'
"Admin Repo" = 'zen-browser --new-tab "https://github.com/h3cksamrat/hydra-den-admin-web/" &'
"Swagger" = 'zen-browser --new-tab "https://roseapi.theasteroid.tech/api-docs" &'


[scratchpads.dolphin]
animation = "fromRight"
command = "dolphin ~/Downloads"
class = "dolphin-float"
lazy = true
size = "40% 90%"
