[pyprland]
plugins = [
  "scratchpads",
  "layout_center",
  "magnify",
  "expose",
  "workspaces_follow_focus",
  "shortcuts_menu",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.topTerm]
animation = "fromTop"
command = "kitty --class kitty-topTerm"
class = "kitty-topTerm"
size = "75% 40%"
lazy =true

[scratchpads.bottomTerm]
animation = "fromBottom"
command = "kitty --class kitty-bottomTerm"
class = "kitty-bottomTerm"
size = "75% 50%"
lazy =true

[scratchpads.mainterm]
animation = "fromBottom"
command = "kitty --class kitty-mainTerm"
class = "kitty-mainTerm"
size = "96% 93%"
pinned = false
lazy = false

[shortcuts_menu.entries]
"Email" = "wl-copy <pass>@<pass>.<pass>"

# [shortcuts_menu.entries.Configs]
"Kitty" = "kitty  nvim ~/.config/kitty/kitty.conf"
"Hypr" = "kitty  nvim ~/.config/hypr/keybindings.conf"
"Scripts" = "kitty  nvim ~/.config/hyprdots/scripts"
"Nvim" = "kitty  nvim ~/.config/nvim"
"Aliases" = "kitty  nvim ~/.config/aliases/.bash_aliases"

[shortcuts_menu.entries."VPN"]
"Username" = "wl-copy <pass>"
"Password" = "wl-copy <pass>"

[shortcuts_menu.entries."NordPass"]
"Password" = "wl-copy <pass>"


[scratchpads.dolphin]
animation = "fromRight"
command = "dolphin ~/Downloads"
class = "dolphin-float"
lazy = true
size = "40% 90%"
