[pyprland]
plugins = [
  "scratchpads",
  "layout_center",
  "magnify",
  "expose",
  "workspaces_follow_focus",
  "shortcuts_menu",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 40%"
lazy =true

[scratchpads.term2]
animation = "fromBottom"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 50%"
lazy =true

[scratchpads.mainterm]
animation = "fromBottom"
command = "kitty --class kitty-dropterm-main"
class = "kitty-dropterm-main"
size = "96% 93%"
lazy = false

[shortcuts_menu.entries]
"LocalHost" = 'firefox --new-tab "http://localhost:3000" &'
"Email" = "wl-copy <email>"
# [shortcuts_menu.entries.Configs]
"Kitty" = "kitty  nvim ~/.config/kitty/kitty.conf"
"Scripts" = "kitty  nvim ~/.config/hyprdots/scripts"
"Hypr" = "kitty  nvim ~/.config/hypr/keybindings.conf"
"Nvim" = "kitty  nvim ~/.config/nvim"
"Aliases" = "kitty  nvim ~/.config/aliases/.bash_aliases"

[shortcuts_menu.entries."VPN"]
"Username" = "wl-copy <username>"
"Password" = "wl-copy <password>"

[shortcuts_menu.entries.Hydra]
"code" = 'kitty --class kitty-dropterm-main  nvim ~/work/hydra-den-web/'
"Web Repo" = 'firefox --new-tab "<link>" &'
"Admin Repo" = 'firefox --new-tab "<link>" &'
"Swagger" = 'firefox --new-tab "<link>" &'

[scratchpads.dolphin]
animation = "fromRight"
command = "dolphin ~/Downloads"
class = "dolphin-float"
lazy = true
size = "40% 90%"
