[pyprland]
plugins = [
  "scratchpads",
  "layout_center",
  "magnify",
  "expose",
  "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 40%"
lazy =true

[scratchpads.term2]
animation = "fromBottom"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 50%"
lazy =true


[scratchpads.mainterm]
animation = "fromBottom"
command = "kitty --class kitty-dropterm-main"
class = "kitty-dropterm-main"
size = "96% 93%"
lazy =false

[scratchpads.htop]
animation = "fromLeft"
command = "kitty --class kitty-htop htop"
class = "kitty-htop"
lazy = true
size = "50% 90%"
unfocus = "hide"

[scratchpads.dolphin]
animation = "fromRight"
command = "dolphin ~/Downloads"
class = "dolphin-float"
lazy = true
size = "40% 90%"
